#!/usr/bin/env python3
"""Validate a workspace generated by android-app-factory."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


class ValidationError(RuntimeError):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", required=True)
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Run structural and Git checks without invoking Gradle.",
    )
    return parser.parse_args()


def require_file(path: Path) -> None:
    if not path.is_file():
        raise ValidationError(f"missing file: {path}")


def run(
    command: list[str],
    cwd: Path,
    env: dict[str, str] | None = None,
) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        env=env,
    )
    if result.returncode != 0:
        raise ValidationError(
            f"command failed in {cwd}: {' '.join(command)}\n{result.stdout.strip()}"
        )
    return result.stdout.strip()


def java_major(java_executable: Path) -> int | None:
    if not java_executable.is_file():
        return None
    result = subprocess.run(
        [str(java_executable), "-version"],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    match = re.search(r'version "([0-9]+)', result.stdout)
    return int(match.group(1)) if match else None


def gradle_environment() -> tuple[dict[str, str], str]:
    candidates: list[Path] = []
    for variable in ("JAVA_HOME", "ANDROID_STUDIO_JDK"):
        value = os.environ.get(variable)
        if value:
            candidates.append(Path(value).expanduser())

    active_java = shutil.which("java")
    if active_java:
        candidates.append(Path(active_java).resolve().parents[1])

    candidates.extend(
        [
            Path("/Applications/Android Studio.app/Contents/jbr/Contents/Home"),
            Path("/Applications/Android Studio Preview.app/Contents/jbr/Contents/Home"),
            Path.home() / "android-studio" / "jbr",
        ]
    )

    checked: set[Path] = set()
    for java_home in candidates:
        resolved = java_home.resolve()
        if resolved in checked:
            continue
        checked.add(resolved)
        java_executable = resolved / "bin" / "java"
        major = java_major(java_executable)
        if major is not None and major >= 17:
            environment = os.environ.copy()
            environment["JAVA_HOME"] = str(resolved)
            environment["PATH"] = str(resolved / "bin") + os.pathsep + environment.get(
                "PATH", ""
            )
            return environment, str(resolved)

    raise ValidationError(
        "Gradle requires JDK 17 or newer. Configure JAVA_HOME or install Android Studio with its bundled JBR."
    )


def validate_git(repo: Path) -> None:
    branch = run(["git", "branch", "--show-current"], cwd=repo)
    if branch != "main":
        raise ValidationError(f"{repo} is on {branch!r}, expected 'main'")
    status = run(["git", "status", "--short"], cwd=repo)
    if status:
        raise ValidationError(f"{repo} has uncommitted changes:\n{status}")
    run(["git", "rev-parse", "--verify", "HEAD"], cwd=repo)


def validate_public_boundary(app_root: Path, legal_root: Path) -> None:
    private_names = {
        "google-services.json",
        "local.properties",
    }
    private_suffixes = {
        ".jks",
        ".keystore",
        ".kt",
        ".kts",
    }
    for path in legal_root.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path.name in private_names or path.suffix in private_suffixes:
            raise ValidationError(f"private app artifact found in public repository: {path}")

    source_root = app_root / "docs" / "legal-source"
    for source_path in source_root.rglob("*"):
        if not source_path.is_file():
            continue
        relative = source_path.relative_to(source_root)
        public_path = legal_root / relative
        require_file(public_path)
        if source_path.read_bytes() != public_path.read_bytes():
            raise ValidationError(f"public legal file drifted from canonical source: {relative}")


def main() -> int:
    try:
        args = parse_args()
        workspace = Path(args.workspace).expanduser().resolve()
        if not workspace.is_dir():
            raise ValidationError(f"workspace does not exist: {workspace}")

        candidates = list(workspace.glob("*/.app-factory/spec.json"))
        if len(candidates) != 1:
            raise ValidationError(
                "expected exactly one child Android repository with .app-factory/spec.json"
            )
        spec_path = candidates[0]
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
        app_root = spec_path.parents[1]
        legal_root = workspace / spec["repositories"]["legal"]
        application_id = spec["app"]["applicationId"]
        package_path = application_id.replace(".", "/")

        required_app_files = (
            "settings.gradle.kts",
            "build.gradle.kts",
            "gradlew",
            "gradle/wrapper/gradle-wrapper.jar",
            "gradle/wrapper/gradle-wrapper.properties",
            "app/build.gradle.kts",
            "app/src/main/AndroidManifest.xml",
            f"app/src/main/java/{package_path}/MainActivity.kt",
            f"app/src/main/java/{package_path}/feature/home/contract/HomeContract.kt",
            f"app/src/main/java/{package_path}/feature/home/presentation/HomeReducer.kt",
            f"app/src/main/java/{package_path}/feature/home/presentation/HomeViewModel.kt",
            f"app/src/main/java/{package_path}/feature/home/ui/HomeScreen.kt",
            "docs/legal-source/privacy-policy.html",
            "docs/legal-source/user-agreement.html",
            "scripts/sync_legal_site.py",
        )
        for relative in required_app_files:
            require_file(app_root / relative)

        required_legal_files = (
            ".app-factory-legal.json",
            ".nojekyll",
            "index.html",
            "privacy-policy.html",
            "user-agreement.html",
            "assets/site.css",
            "en/index.html",
            "en/privacy-policy.html",
            "en/user-agreement.html",
            "zh-CN/index.html",
            "zh-CN/privacy-policy.html",
            "zh-CN/user-agreement.html",
        )
        for relative in required_legal_files:
            require_file(legal_root / relative)

        validate_public_boundary(app_root, legal_root)

        app_build = (app_root / "app" / "build.gradle.kts").read_text(
            encoding="utf-8"
        )
        if "pulse.mvi.platform.android.compose" not in app_build:
            raise ValidationError("pulse Compose dependency is missing")
        forbidden_dependencies = ("firebase", "play-services-ads", "mlkit")
        for dependency in forbidden_dependencies:
            if dependency in app_build.lower():
                raise ValidationError(
                    f"business-specific dependency found in minimal shell: {dependency}"
                )

        for locale in spec["app"]["androidLocales"]:
            folder_map = {
                "en": "values",
                "zh-CN": "values-zh-rCN",
                "zh-Hant": "values-b+zh+Hant",
                "es": "values-es",
                "pt-BR": "values-pt-rBR",
                "hi": "values-hi",
                "ur": "values-ur",
                "fr": "values-fr",
                "ja": "values-ja",
                "ko": "values-ko",
                "id": "values-in",
                "th": "values-th",
                "vi": "values-vi",
                "ms": "values-ms",
                "fil": "values-b+fil",
            }
            require_file(
                app_root
                / "app"
                / "src"
                / "main"
                / "res"
                / folder_map[locale]
                / "strings.xml"
            )

        if (app_root / ".git").is_dir():
            validate_git(app_root)
        if (legal_root / ".git").is_dir():
            validate_git(legal_root)

        java_home = None
        if not args.skip_build:
            environment, java_home = gradle_environment()
            run(
                ["./gradlew", ":app:testDebugUnitTest", ":app:assembleDebug"],
                cwd=app_root,
                env=environment,
            )

        result = {
            "workspace": str(workspace),
            "androidRepository": str(app_root),
            "legalRepository": str(legal_root),
            "structure": "passed",
            "git": "passed"
            if (app_root / ".git").is_dir() and (legal_root / ".git").is_dir()
            else "not-initialized",
            "gradle": "skipped" if args.skip_build else "passed",
            "javaHome": java_home,
        }
        print(json.dumps(result, indent=2))
        return 0
    except (ValidationError, KeyError, json.JSONDecodeError) as error:
        print(f"android-app-factory validation failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
