#!/usr/bin/env python3
"""Validate a workspace generated by android-app-factory."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path


class ValidationError(RuntimeError):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", required=True)
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Run structural and Git checks without invoking Gradle.",
    )
    parser.add_argument(
        "--platform-source",
        help="Use a local Magic Android Platform composite only for Factory acceptance validation.",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Use only already-cached Gradle dependencies during validation.",
    )
    return parser.parse_args()


def require_file(path: Path) -> None:
    if not path.is_file():
        raise ValidationError(f"missing file: {path}")


def run(
    command: list[str],
    cwd: Path,
    env: dict[str, str] | None = None,
) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        env=env,
    )
    if result.returncode != 0:
        raise ValidationError(
            f"command failed in {cwd}: {' '.join(command)}\n{result.stdout.strip()}"
        )
    return result.stdout.strip()


def java_major(java_executable: Path) -> int | None:
    if not java_executable.is_file():
        return None
    result = subprocess.run(
        [str(java_executable), "-version"],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    match = re.search(r'version "([0-9]+)', result.stdout)
    return int(match.group(1)) if match else None


def gradle_environment() -> tuple[dict[str, str], str]:
    candidates: list[Path] = []
    for variable in ("JAVA_HOME", "ANDROID_STUDIO_JDK"):
        value = os.environ.get(variable)
        if value:
            candidates.append(Path(value).expanduser())

    active_java = shutil.which("java")
    if active_java:
        candidates.append(Path(active_java).resolve().parents[1])

    candidates.extend(
        [
            Path("/Applications/Android Studio.app/Contents/jbr/Contents/Home"),
            Path("/Applications/Android Studio Preview.app/Contents/jbr/Contents/Home"),
            Path.home() / "android-studio" / "jbr",
        ]
    )
    candidates.extend(
        sorted((Path.home() / ".gradle" / "jdks").glob("*/*/Contents/Home"))
    )

    checked: set[Path] = set()
    for java_home in candidates:
        resolved = java_home.resolve()
        if resolved in checked:
            continue
        checked.add(resolved)
        java_executable = resolved / "bin" / "java"
        major = java_major(java_executable)
        if major is not None and major >= 17:
            environment = os.environ.copy()
            environment["JAVA_HOME"] = str(resolved)
            environment["PATH"] = str(resolved / "bin") + os.pathsep + environment.get(
                "PATH", ""
            )
            return environment, str(resolved)

    raise ValidationError(
        "Gradle requires JDK 17 or newer. Configure JAVA_HOME or install Android Studio with its bundled JBR."
    )


def validate_git(repo: Path) -> None:
    branch = run(["git", "branch", "--show-current"], cwd=repo)
    if branch != "main":
        raise ValidationError(f"{repo} is on {branch!r}, expected 'main'")
    status = run(["git", "status", "--short"], cwd=repo)
    if status:
        raise ValidationError(f"{repo} has uncommitted changes:\n{status}")
    run(["git", "rev-parse", "--verify", "HEAD"], cwd=repo)


def validate_public_boundary(app_root: Path, legal_root: Path) -> None:
    private_names = {
        "google-services.json",
        "local.properties",
    }
    private_suffixes = {
        ".jks",
        ".keystore",
        ".kt",
        ".kts",
    }
    for path in legal_root.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path.name in private_names or path.suffix in private_suffixes:
            raise ValidationError(f"private app artifact found in public repository: {path}")

    source_root = app_root / "publishing" / "legal"
    for source_path in source_root.rglob("*"):
        if not source_path.is_file():
            continue
        relative = source_path.relative_to(source_root)
        public_path = legal_root / relative
        require_file(public_path)
        if source_path.read_bytes() != public_path.read_bytes():
            raise ValidationError(f"public legal file drifted from canonical source: {relative}")


def gradle_block(source: str, name: str) -> str:
    start = source.find(name)
    if start < 0:
        raise ValidationError(f"missing Gradle block: {name}")
    opening = source.find("{", start + len(name))
    if opening < 0:
        raise ValidationError(f"missing opening brace for Gradle block: {name}")

    depth = 0
    for index in range(opening, len(source)):
        character = source[index]
        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return source[opening + 1 : index]
    raise ValidationError(f"unclosed Gradle block: {name}")


def validate_google_repository_filters(settings: str) -> None:
    required_groups = (
        'includeGroupByRegex("com\\\\.android.*")',
        'includeGroupByRegex("com\\\\.google.*")',
        'includeGroupByRegex("androidx.*")',
    )
    for section_name in ("pluginManagement", "dependencyResolutionManagement"):
        section = gradle_block(settings, section_name)
        if "google()" in section:
            raise ValidationError(
                f"{section_name} must not use an unfiltered Google repository"
            )
        google_repository = gradle_block(section, "google")
        content_filter = gradle_block(google_repository, "content")
        for group in required_groups:
            if group not in content_filter:
                raise ValidationError(
                    f"{section_name} Google repository filter is missing: {group}"
                )


def main() -> int:
    try:
        args = parse_args()
        workspace = Path(args.workspace).expanduser().resolve()
        if not workspace.is_dir():
            raise ValidationError(f"workspace does not exist: {workspace}")

        candidates = list(workspace.glob("*/.app-factory/spec.json"))
        if len(candidates) != 1:
            raise ValidationError(
                "expected exactly one child Android repository with .app-factory/spec.json"
            )
        spec_path = candidates[0]
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
        if spec.get("schemaVersion") != 2:
            raise ValidationError("unsupported Factory spec schema; expected version 2")
        app_root = spec_path.parents[1]
        legal_root = workspace / spec["repositories"]["legal"]
        application_id = spec["app"]["applicationId"]
        package_path = application_id.replace(".", "/")

        required_app_files = (
            "settings.gradle.kts",
            "build.gradle.kts",
            "gradlew",
            "gradle/wrapper/gradle-wrapper.jar",
            "gradle/wrapper/gradle-wrapper.properties",
            "app/build.gradle.kts",
            "app/src/main/AndroidManifest.xml",
            f"app/src/main/java/{package_path}/MainActivity.kt",
            f"app/src/main/java/{package_path}/feature/home/contract/HomeContract.kt",
            f"app/src/main/java/{package_path}/feature/home/presentation/HomeMutation.kt",
            f"app/src/main/java/{package_path}/feature/home/presentation/HomeViewModel.kt",
            f"app/src/main/java/{package_path}/feature/home/ui/HomeScreen.kt",
            f"app/src/test/java/{package_path}/feature/home/presentation/HomeMutationReducerTest.kt",
            "docs/README.md",
            "docs/product/product-requirements.md",
            "docs/engineering/architecture.md",
            "docs/engineering/testing.md",
            "docs/operations/README.md",
            "docs/decisions/README.md",
            "tools/README.md",
            "tools/repository/validate_layout.py",
            "tools/repository/tests/test_validate_layout.py",
            "tools/publishing/legal/sync_to_legal_repo.py",
            "publishing/README.md",
            "publishing/legal/privacy-policy.html",
            "publishing/legal/user-agreement.html",
            ".github/workflows/repository-layout.yml",
        )
        for relative in required_app_files:
            require_file(app_root / relative)

        required_legal_files = (
            ".app-factory-legal.json",
            ".nojekyll",
            "index.html",
            "privacy-policy.html",
            "user-agreement.html",
            "assets/site.css",
            "en/index.html",
            "en/privacy-policy.html",
            "en/user-agreement.html",
            "zh-CN/index.html",
            "zh-CN/privacy-policy.html",
            "zh-CN/user-agreement.html",
        )
        for relative in required_legal_files:
            require_file(legal_root / relative)

        validate_public_boundary(app_root, legal_root)
        run(
            [
                "python3",
                "-m",
                "unittest",
                "discover",
                "-s",
                "tools/repository/tests",
                "-p",
                "test_*.py",
            ],
            cwd=app_root,
        )
        run(["python3", "tools/repository/validate_layout.py"], cwd=app_root)

        settings = (app_root / "settings.gradle.kts").read_text(encoding="utf-8")
        validate_google_repository_filters(settings)

        app_build = (app_root / "app" / "build.gradle.kts").read_text(
            encoding="utf-8"
        )
        root_build = (app_root / "build.gradle.kts").read_text(encoding="utf-8")
        required_plugins = (
            "io.github.magic-xu.magic-android-application",
            "io.github.magic-xu.magic-android-compose",
            "io.github.magic-xu.magic-android-pulse",
            "io.github.magic-xu.magic-android-quality",
        )
        for plugin_id in required_plugins:
            if plugin_id not in root_build or plugin_id not in app_build:
                raise ValidationError(f"required platform plugin is missing: {plugin_id}")
        platform = spec.get("platform", {})
        platform_version = platform.get("version")
        if not isinstance(platform_version, str) or not re.fullmatch(
            r"[1-9][0-9]*\.[0-9]+\.[0-9]+", platform_version
        ):
            raise ValidationError("spec must pin a released stable platform x.y.z version")
        if platform.get("qualityPolicy") != "mandatory":
            raise ValidationError("platform quality policy must be mandatory")
        if f'version "{platform_version}"' not in root_build:
            raise ValidationError("root plugin versions do not match the Factory spec")
        if "magicQuality" in app_build or "magicQuality" in root_build:
            raise ValidationError("generated apps cannot configure quality-rule exemptions")
        if "com.android.application" in app_build or "org.jetbrains.kotlin" in app_build:
            raise ValidationError("app bypasses the shared platform build baseline")
        if "io.github.magic-xu:mvi-" in app_build:
            raise ValidationError("app bypasses the platform-owned Pulse baseline")
        forbidden_dependencies = ("firebase", "play-services-ads", "mlkit")
        for dependency in forbidden_dependencies:
            if dependency in app_build.lower():
                raise ValidationError(
                    f"business-specific dependency found in minimal shell: {dependency}"
                )

        for locale in spec["app"]["androidLocales"]:
            folder_map = {
                "en": "values",
                "zh-CN": "values-zh-rCN",
                "zh-Hant": "values-b+zh+Hant",
                "es": "values-es",
                "pt-BR": "values-pt-rBR",
                "hi": "values-hi",
                "ur": "values-ur",
                "fr": "values-fr",
                "ja": "values-ja",
                "ko": "values-ko",
                "id": "values-in",
                "th": "values-th",
                "vi": "values-vi",
                "ms": "values-ms",
                "fil": "values-b+fil",
            }
            require_file(
                app_root
                / "app"
                / "src"
                / "main"
                / "res"
                / folder_map[locale]
                / "strings.xml"
            )

        if (app_root / ".git").is_dir():
            validate_git(app_root)
        if (legal_root / ".git").is_dir():
            validate_git(legal_root)

        java_home = None
        if not args.skip_build:
            environment, java_home = gradle_environment()
            gradle_command = ["./gradlew"]
            if args.offline:
                gradle_command.append("--offline")
            if args.platform_source:
                platform_source = Path(args.platform_source).expanduser().resolve()
                if not (platform_source / "settings.gradle.kts").is_file():
                    raise ValidationError(
                        f"invalid Magic Android Platform source: {platform_source}"
                    )
                gradle_command.extend(["--include-build", str(platform_source)])
            gradle_command.extend(
                [
                    "check",
                    ":app:assembleDebug",
                    ":app:assembleRelease",
                    ":app:bundleRelease",
                ]
            )
            run(
                gradle_command,
                cwd=app_root,
                env=environment,
            )

        result = {
            "workspace": str(workspace),
            "androidRepository": str(app_root),
            "legalRepository": str(legal_root),
            "structure": "passed",
            "repositoryLayout": "passed",
            "git": "passed"
            if (app_root / ".git").is_dir() and (legal_root / ".git").is_dir()
            else "not-initialized",
            "gradle": "skipped" if args.skip_build else "passed",
            "javaHome": java_home,
        }
        print(json.dumps(result, indent=2))
        return 0
    except (ValidationError, KeyError, json.JSONDecodeError) as error:
        print(f"android-app-factory validation failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
